export enum ParametroEnum {
  CD_PRECO_PADRAO = 'CD_PRECO_PADRAO',
  QT_DIAS_TROCA = 'QT_DIAS_TROCA',
  QT_DIAS_DEVOLUCAO = 'QT_DIAS_DEVOLUCAO',
  OBS_PADRAO_COMPRA = 'OBS_PADRAO_COMPRA',
  OBS_PADRAO_VENDA = 'OBS_PADRAO_VENDA',
  OBS_PADRAO_CONSIGNACAO = 'OBS_PADRAO_CONSIGNACAO',
  DEVOLVER_SEM_ROMANEIO = 'DEVOLVER_SEM_ROMANEIO',
  FATURAR_PEDIDO_SEM_CONFERENCIA = 'FATURAR_PEDIDO_SEM_CONFERENCIA',
  INTEGRACAO_OPEN_PIX_HABILITADA = 'INTEGRACAO_OPEN_PIX_HABILITADA',
  INTEGRACAO_OPEN_PIX_APP_ID = 'INTEGRACAO_OPEN_PIX_APP_ID',
  INTEGRACAO_INFINITY_PAY_HABILITADA = 'INTEGRACAO_INFINITY_PAY_HABILITADA',
  INTEGRACAO_INFINITY_PAY_API_HANDLE = 'INTEGRACAO_INFINITY_PAY_API_HANDLE',
  INTEGRACAO_INFINITY_PAY_URL_REDIRECT = 'INTEGRACAO_INFINITY_PAY_URL_REDIRECT',
  INTEGRACAO_INFINITY_PAY_URL_WEBHOOK = 'INTEGRACAO_INFINITY_PAY_URL_WEBHOOK',
  URL_SITE_EMPRESA = 'URL_SITE_EMPRESA',
}

export type Parametro = keyof typeof ParametroEnum;
